### ISSUE TITLE
Resource Leak

### ISSUE THREAD

**Issue by bicky21** [king04aman/KeyLogger#2]
In Cryptoraphy/generatekey.py: 
The code opens a file to write the encryption key but doesn't use a context manager (**with** statement) to ensure that the file is properly closed after writing the key. While the code does close the file explicitly with **file.close()**, it's safer to use a with statement to handle the file, which will automatically close it even if an exception occurs.

**Comment by king04aman** [comment]
Thank you for bringing this to my attention. I appreciate your feedback and I'll make sure to implement the "with" statement in update for better file handling in the Cryptography/generatekey.py script.
